* Why
When I wrote this, I had found out about the repository [[https://github.com/papis/papis][papis]] which is pretty nice. However, when I checked out the [[https://github.com/papis/papis-zotero][papis-zotero]] repository, I realized that the repository was a bit outdated, some of its documentation was a little outdated, and it didn't particularly do what I wanted it to do. To my understanding, the package described in [[https://github.com/papis/papis-zotero][papis-zotero]] is setup to do a single copy of the files described in the =zotero.sqlite=. But the problem is that not all of the attachments are copied over, and the way the files are organized is that it saves the database keys as the names of the folders where the PDF files end up being copied to.

What I particularly wanted was a tool which allowed one to parse the information from Zotero to papis in a way that it would keep some sort of human-readable file structure, and keep the attachments used on Zotero. How I then decided to design this is to make this a one-way workflow which looks through the SQLite file from Zotero, and copies them over to the papis directory.

* Installation




